name: Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build_and_release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --bin fake --features cli
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: target/release/fake
